GeekZoneHQ/web

.circleci/config.yml

We have shut down everything on AWS to keep costs down while we are
doing development, so the other stages of the build would just fail.
For now we are just doing build and test which should be sufficient for
now.

Simplify the circleci build for now

---

web/urls.py
web/views.py

create logout flow

---

memberships/forms.py
memberships/templates/memberships/register.html
memberships/tests/test_registration_form.py
web/settings.py

Minimum length requirement done. 
Need to recaptcha. Will split into its own issue.

Min password length

---

memberships/static/memberships/css/main.css
memberships/static/memberships/js/main.js
memberships/templates/base.html
memberships/templates/memberships/404.html
memberships/templates/memberships/confirm.html
memberships/templates/memberships/home.html
memberships/templates/memberships/login.html
memberships/templates/memberships/logout.html
memberships/templates/memberships/member_details.html
memberships/templates/memberships/member_settings.html
memberships/templates/memberships/register.html

So this ended up being a bundle of stuff.
- General tidy-up of HTML files - rearranging tags, indenting, line spacing, etc.
- Added and linked a new JS file.
- Improved general styling, e.g. header colors, form presentation, narrower content width.
- Fixed copyleft symbol for Firefox on Windows (and possibly other browsers).
- Implemented sticky header (credit to @bishira14 for the suggestion).
- Implemented basic dark mode (with temporary toggle button).
Resolves #98 (dark mode) - and possibly #96 since it's been split up?
This is my first pull request so let me know if I'm doing this right...

General styling, inc. dark mode, sticky banner

---

readme.md

These are some improvements to the setup docs, see the commit messages for more detail. This only covers ubuntu based linux distributions, and does not touch on configuration or payments setup.
I plan on doing the windows docs next, and the configuration and payments after that.

Development doc improvements

---

readme.md

This is mostly similar to the Ubuntu Linux instructions, but with some
specific information about running under windows.
This information includes:
* Where/How to install git
* How to install Python
* How to activate a virtual environment in Windows
As per the Ubuntu docs this guide does not cover configuring the
membership management system using the `.env` file. I intend to create
a guide for that next.

Windows setup docs

---

memberships/context_processors.py
memberships/templates/base.html
memberships/templates/memberships/register.html
memberships/tests/test_login_form.py
memberships/tests/test_registration_form.py
memberships/views.py
web/settings.py

Hey guys, here's the recpatchav3 if you could have a look at it. To go to the register page you have to go /memberships/logout. The next part after registration doesn't work (39 has been done now but wasn't at the time), so basically if you don't get a 403 error it thinks you're human.

Recaptchav3

---

memberships/static/memberships/css/main.css
memberships/templates/base.html
memberships/templates/memberships/login.html
memberships/templates/memberships/member_details.html
memberships/templates/memberships/register.html
requirements.txt
web/settings.py

- centered the login form
- centred the registration form
- navbar responsive using bootstrap
resolves #107, resolves #108, resolves #133

centered login, registration form and navbar reponsive

---

memberships/templates/memberships/humans.txt

Testing GPG verification (tbentham)

---

memberships/email.py
memberships/tasks.py
memberships/templates/memberships/email_message.html
readme.md
requirements.txt
web/celery.py
web/settings.py

Creates the task_send_email function in memberships/tasks.py to allow other functions to send email via Celery & Rabbit MQ. Resolves #147

Updated send email

---

readme.md

I think we can all agree that it is imperative that this typo is fixed... as I can't stand looking at it much longer :)

Typo in README

---

memberships/email.py
readme.md

Minor fixes for task queuing

---

memberships/static/js/main.js
memberships/templates/base.html
memberships/templates/inc/help_text.html
theme/static_src/tailwind.config.js

Changes:
* Fixed issues with dark mode and other stylings, caused by Tailwind over-purging CSS.
* Omitted `Arial Black` from fallback fonts, which was being converted to `Arial #000` in the production build.
Minor:
* Resolved accessibility issues raised by Edge in the browser.

Tailwind build fixes

---

memberships/templates/memberships/login.html
memberships/templates/memberships/member_settings.html
memberships/templates/memberships/register.html

Fixes #307.
Simple fix - turns out I just forgot to render non-field errors.

Adding non-field errors to forms

---

.circleci/config.yml

This adds bug branches to build in the ci/cd pipeline

---

.circleci/config.yml
docker-compose.yml
readme.md

This changes the docker-compose file by removing the volume from postgres db service and adding one in the web service instead. 
Also the readme.md has been modified to show the configuration to run the project in docker as a first option. 
"resolves #463 -->

This solves issue 463

---

.github/pull_request_template.md

One line change to the right link.
Just tested the link.

Fixed wrong link to contributing.md (#452)

---

docker-compose.yml
docker/backend/Dockerfile

Some instructions in the Dockerfile were in the wrong order. This resulted in files and folders in the container belonging to the root user instead of the django user, and with wrong permissions.
With the changes made to the Dockerfile the ownership and permissions of files and folders in the container have been corrected. 
This has been verified by running the following commands in the container launched by docker-compose:
- `docker exec -it backend sh`
- `ls -l`
- `whoami`
- [xI have read the **[CONTRIBUTING](https://github.com/GeekZoneHQ/web/blob/master/CONTRIBUTING.md)** document.

Modify Dockerfile to change ownership and permissions in container file system

---

.circleci/config.yml
k8s/test-environment/deploy-test.yaml

Description
Whenever a branch named feature-* is created and a PR is raised from that branch, a namespace is automatically created in the geekzone aws cluster. This namespace is populated with a deployment of the django app, a service to make that deployment reachable and an ingress that allows sending traffic from the internet to the django app. This namespace is created for testing.
Related Issue
#330
Motivation and Context
This change make it easy to test a new feature on the fly, without affecting resources running in production

This adds configuration to create a namespace for testing

---

.circleci/config.yml

Currently doc-* branches are excluded from the cicd workflow, thus preventing them from being merged into the master branch. Also, the current configuration does not allow to deploy to Azure. 
The changes brought here solve the above issues and rename the cicd workflow from "main" to "main-web" to differenciate it from the one running in the infra repo.
"resolves #542" and "resolves #545"

Allow cicd from doc-* branches and add config to deploy to Azure

---

.circleci/config.yml
.circleci/config.yml.aws

The deploy-prod in cicd is failing due to a wrong piece of code pasted in place of the right one. 
"resolves #571" 
The configuration was adapted to that of the deploy-test job that runs successfully.

This fixes deploy-prod job in cicd

---

.circleci/config.yml
docker/backend/Dockerfile
docker/development/Dockerfile
docker/proxy/Dockerfile

Update Python version in Dockerfile/s to solve critical vulnerability issue.
"resolves #613"
The Circle ci/cd pipeline failed because Snyk found a critical vulnerability linked to expat/expat, which was introduced by the Python version that is currently used as a base image in the Dockerfile.

This updates the Python version across the Dockerfiles

---

.circleci/config.yml
docker-compose.yml
docker/backend/Dockerfile
requirements.txt

This updates some dependencies as suggested by the Snyk scans, which had failed due to an expired token.
Updated dependencies versions in requirements.txt and in Dockerfile. 
#670 
Currently Snyk checks and Circleci pipeline fail due to critical vulnerabilities detected.
Through Circleci pipeline.

Fix cicd pipeline

---

docker/development/Dockerfile
requirements.txt

#683" -->
Prevent Snyk from failing the cicd pipeline

Updated dependencies version to fix vulnerability

---

.github/workflows/eisenhower.yml
.github/workflows/snyk.yaml
requirements.txt

The Eisenhower prioritisation issue now requires the triggering issue to be passed in. This provides that.
Only real change is the addition of
`GH_ISSUE_NUMBER: ${{ github.event.issue.number }}`
resolves #685 
Makes the action more efficient by only processing the trigger issue. Should prevent us from hitting rate limits.
Existing logic not changed, only updates the issues that it processes.

web-685 update eisenhower action to include trigger issue

---

.circleci/config.yml
docker/backend/Dockerfile
docker/development/Dockerfile
docker/proxy/Dockerfile
requirements.txt

Updated dependencies version in requirements.txt and backend Dockerfile
"resolves #728"
It allows Snyk to pass its check on the cicd pipeline
It has been tested by successfully run a build in the cicd pipeline

Update dependencies version
